### ISSUE TITLE
Info sobre alteração de imagem

### ISSUE THREAD

**Issue by rehv** [storiify/Storiify#19]
Código de imagem "padrão":
`<div class="col-sm-12">
                                                <img src="imagens/100no_photo.png" class="img-circle imgClicavel col-sm-offset-5" />
                                                <a class="imgReset col-sm-offset-5"><i class="fa fa-ban"></i></a>
                                            </div>`

Código de imagem adicionado:
`<img src="imagens/100no_photo.png" class="img-circle imgClicavel col-sm-offset-5" data-inputFileId="imgPrincipal"/>
					    <input type='file' id="imgPrincipal" name="imagem_insp" style="display:none;" />
					    <a class="imgReset col-sm-offset-5"><i class="fa fa-ban"></i></a>`

@yanznho Gostaria de saber o porquê da alteração? Vlw

**Comment by yanznho** [comment]
Ta perguntando porque coloquei o input ai?

**Comment by rehv** [comment]
Yes, sir. Estou padronizando todo o código, quero saber o porquê pra saber se tem que mudar nos outros.

**Comment by rehv** [comment]
Respondido via grupo.
