### ISSUE TITLE
Input File de imagem esta com limitação de png

### ISSUE THREAD

**Issue by yanznho** [storiify/Storiify#59]
alem de png deve aceitar tbm jpg, jpeg e gif pelo menos.

**Comment by rehv** [comment]
Estava limitado a apenas um tipo de arquivo por um motivo (métodos de criação e exclusão dos arquivos). Antes de aceitar outras extensões, estes métodos devem ser alterados para que funcionem com qualquer tipo de extensão.

Eu irei alterar isto antes de aceitar o PR/commit e fechar a issue, já tenho a solução.

**Comment by rehv** [comment]
Consertado em c93649c85bca374d97a2402820e386a5739c2e54
