### ISSUE TITLE
Sistema tenta acessar dados da sessão sem o usuário estar logado

### ISSUE THREAD

**Issue by rehv** [storiify/Storiify#61]
Problema provavelmente no ModeloHistoria.php , visto que está acessando o método listar história na página de login.

@yanznho marcando para vc tomar ciência. Me diga se tem alguma ideia do que pode ser, senão eu procuro pra alterar.

**Comment by yanznho** [comment]
Ta certo, fui eu que fiz isso...

**Comment by rehv** [comment]
OK, mas não entendi. Porque você precisa entrar na ação de listar histórias se não tem nenhum usuário logado? E outra coisa, isso tem outros problemas porque vc não trata uma sessão inválida tbm, novo login etc. Temos que corrigir isso ASAP.

**Comment by rehv** [comment]
@yanznho preciso de uma atualização disso aqui, já que vc identificou a necessidade de correção na sexta-feira.

**Comment by rehv** [comment]
Resolvido
